name: GitActions Demo1
on: push
jobs:
  GitActions-demo-jobs:
    name: Demo jobs
    runs-on: ubuntu-latest
    steps:
      - name: Print a enviroment
        env:
          MY_VAR: Hi There! My name is
          FIRST_NAME: pyoungoh
          LAST_NAME: park
          AWS_JOB_NAME: popark.park
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
          echo $MY_VAR $AWS_JOB_NAME.
